def on_forever():
    basic.show_number(0)
    basic.pause(500)
    basic.show_number(2)
    basic.pause(500)
    basic.show_number(4)
    basic.pause(500)
    basic.show_number(6)
    basic.show_number(8)
    basic.pause(500)
    basic.show_number(10)
    basic.pause(500)
    basic.show_number(12)
basic.forever(on_forever)
