basic.forever(function () {
    basic.showNumber(0)
    basic.pause(500)
    basic.showNumber(2)
    basic.pause(500)
    basic.showNumber(4)
    basic.pause(500)
    basic.showNumber(6)
    basic.showNumber(8)
    basic.pause(500)
    basic.showNumber(10)
    basic.pause(500)
    basic.showNumber(12)
})
